version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: jujuba_bd
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jujuba_brecho
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: ./jujuba_backend
      dockerfile: Dockerfile 
    container_name: jujuba_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/jujuba_brecho?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./jujuba_frontend
      dockerfile: Dockerfile
    container_name: jujuba_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080/
    volumes:
      - ./jujuba_frontend:/app
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge