# Usa uma imagem leve do Node.js
FROM node:18-alpine


WORKDIR /app


COPY package.json package-lock.json ./


RUN npm install


COPY . .


ENV NEXT_PUBLIC_API_URL=http://backend:8080


EXPOSE 3000


CMD ["npm", "run", "dev"]
